# Generated by Django 4.1.3 on 2024-07-27 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='created_at',
        ),
    ]
